name: PR Cleanup

on:
  pull_request:
    types: [closed]

permissions:
  packages: write

jobs:
  cleanup-ghcr:
    name: Delete PR Container Image from GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Delete PR tag from GitHub Packages
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: cellular-wan-gateway
          delete-tags: "pr-${{ github.event.pull_request.number }}"
        continue-on-error: true
